# Form implementation generated from reading ui file 'VoiceTextWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VoiceTextWindow(object):
    def setupUi(self, VoiceTextWindow):
        VoiceTextWindow.setObjectName("VoiceTextWindow")
        VoiceTextWindow.resize(450, 100)
        VoiceTextWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(parent=VoiceTextWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(15, 0, 15, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        VoiceTextWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(VoiceTextWindow)
        QtCore.QMetaObject.connectSlotsByName(VoiceTextWindow)

    def retranslateUi(self, VoiceTextWindow):
        _translate = QtCore.QCoreApplication.translate
        VoiceTextWindow.setWindowTitle(_translate("VoiceTextWindow", "VoiceTextWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoiceTextWindow = QtWidgets.QMainWindow()
    ui = Ui_VoiceTextWindow()
    ui.setupUi(VoiceTextWindow)
    VoiceTextWindow.show()
    sys.exit(app.exec())
